[package]
name = "pycel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pycel"
crate-type = ["cdylib"]

[dependencies]
cel-interpreter = "0.4.1"
pyo3 = "0.19.0"
